package com.example.idutil.distributedidgenerator.mapper;

import com.example.idutil.distributedidgenerator.entity.Idgenerator;

public interface IdgeneratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idgenerator
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idgenerator
     *
     * @mbggenerated
     */
    int insert(Idgenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idgenerator
     *
     * @mbggenerated
     */
    int insertSelective(Idgenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idgenerator
     *
     * @mbggenerated
     */
    Idgenerator selectByPrimaryKey(String tableName);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idgenerator
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Idgenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idgenerator
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Idgenerator record);
}