package com.example.idutil.distributedidgenerator.entity;

public class Idgenerator {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idgenerator.table_name
     *
     * @mbggenerated
     */
    private String tableName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idgenerator.current_value
     *
     * @mbggenerated
     */
    private Long currentValue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idgenerator.table_name
     *
     * @return the value of idgenerator.table_name
     *
     * @mbggenerated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idgenerator.table_name
     *
     * @param tableName the value for idgenerator.table_name
     *
     * @mbggenerated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idgenerator.current_value
     *
     * @return the value of idgenerator.current_value
     *
     * @mbggenerated
     */
    public Long getCurrentValue() {
        return currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idgenerator.current_value
     *
     * @param currentValue the value for idgenerator.current_value
     *
     * @mbggenerated
     */
    public void setCurrentValue(Long currentValue) {
        this.currentValue = currentValue;
    }
}